name: Frontend workflow

on:
  push:
    branches:
      - master
      - main

jobs:
  workflow:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push version tag
        uses: falokut/version-tag-action@v1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        uses: falokut/docker-image-action@v1
        with:
          image_name: ${{ github.event.repository.name }}
          registry_username: ${{ secrets.DOCKER_USERNAME }}
          registry_password: ${{ secrets.DOCKER_PASSWORD }}
